//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2024-11-15 12:39:28
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for AirportLocation in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AirportLocation")]
    public partial class AirportLocation : Location
    {
        /// <summary>
        /// There are no comments for Property Loc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Loc")]
        public virtual global::Microsoft.Spatial.GeographyPoint Loc
        {
            get
            {
                return this._Loc;
            }
            set
            {
                this.OnLocChanging(value);
                this._Loc = value;
                this.OnLocChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Spatial.GeographyPoint _Loc;
        partial void OnLocChanging(global::Microsoft.Spatial.GeographyPoint value);
        partial void OnLocChanged();
    }
}
