//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/13/2024 12:10:48
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for AirportSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AirportSingle")]
    public partial class AirportSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Airport>
    {
        /// <summary>
        /// Initialize a new AirportSingle object.
        /// </summary>
        public AirportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AirportSingle object.
        /// </summary>
        public AirportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AirportSingle object.
        /// </summary>
        public AirportSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Airport> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Airport in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IcaoCode
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("IcaoCode")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Airport")]
    public partial class Airport : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Airport object.
        /// </summary>
        /// <param name="icaoCode">Initial value of IcaoCode.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="iataCode">Initial value of IataCode.</param>
        /// <param name="location">Initial value of Location.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Airport CreateAirport(string icaoCode, string name, string iataCode, global::FluentUI.TripPin.Model.AirportLocation location)
        {
            Airport airport = new Airport();
            airport.IcaoCode = icaoCode;
            airport.Name = name;
            airport.IataCode = iataCode;
            if ((location == null))
            {
                throw new global::System.ArgumentNullException("location");
            }
            airport.Location = location;
            return airport;
        }
        /// <summary>
        /// There are no comments for Property IcaoCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IcaoCode")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IcaoCode is required.")]
        public virtual string IcaoCode
        {
            get
            {
                return this._IcaoCode;
            }
            set
            {
                this.OnIcaoCodeChanging(value);
                this._IcaoCode = value;
                this.OnIcaoCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _IcaoCode;
        partial void OnIcaoCodeChanging(string value);
        partial void OnIcaoCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property IataCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IataCode")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IataCode is required.")]
        public virtual string IataCode
        {
            get
            {
                return this._IataCode;
            }
            set
            {
                this.OnIataCodeChanging(value);
                this._IataCode = value;
                this.OnIataCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _IataCode;
        partial void OnIataCodeChanging(string value);
        partial void OnIataCodeChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Location is required.")]
        public virtual global::FluentUI.TripPin.Model.AirportLocation Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::FluentUI.TripPin.Model.AirportLocation _Location;
        partial void OnLocationChanging(global::FluentUI.TripPin.Model.AirportLocation value);
        partial void OnLocationChanged();
    }
}
