//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2024-11-15 12:39:28
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for EmployeeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EmployeeSingle")]
    public partial class EmployeeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Employee>
    {
        /// <summary>
        /// Initialize a new EmployeeSingle object.
        /// </summary>
        public EmployeeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new EmployeeSingle object.
        /// </summary>
        public EmployeeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new EmployeeSingle object.
        /// </summary>
        public EmployeeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Employee> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Peers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Peers")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> Peers
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Peers == null))
                {
                    this._Peers = Context.CreateQuery<global::FluentUI.TripPin.Model.Person>(GetPath("Peers"));
                }
                return this._Peers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> _Peers;
        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Friends")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> Friends
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Friends == null))
                {
                    this._Friends = Context.CreateQuery<global::FluentUI.TripPin.Model.Person>(GetPath("Friends"));
                }
                return this._Friends;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> _Friends;
        /// <summary>
        /// There are no comments for BestFriend in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BestFriend")]
        public virtual global::FluentUI.TripPin.Model.PersonSingle BestFriend
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BestFriend == null))
                {
                    this._BestFriend = new global::FluentUI.TripPin.Model.PersonSingle(this.Context, GetPath("BestFriend"));
                }
                return this._BestFriend;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::FluentUI.TripPin.Model.PersonSingle _BestFriend;
        /// <summary>
        /// There are no comments for Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Trips")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Trip> Trips
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Trips == null))
                {
                    this._Trips = Context.CreateQuery<global::FluentUI.TripPin.Model.Trip>(GetPath("Trips"));
                }
                return this._Trips;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Trip> _Trips;
    }
    /// <summary>
    /// There are no comments for Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("UserName")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Employee")]
    public partial class Employee : Person
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="gender">Initial value of Gender.</param>
        /// <param name="favoriteFeature">Initial value of FavoriteFeature.</param>
        /// <param name="cost">Initial value of Cost.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Employee CreateEmployee(string userName, string firstName, global::FluentUI.TripPin.Model.PersonGender gender, global::FluentUI.TripPin.Model.Feature favoriteFeature, long cost)
        {
            Employee employee = new Employee();
            employee.UserName = userName;
            employee.FirstName = firstName;
            employee.Gender = gender;
            employee.FavoriteFeature = favoriteFeature;
            employee.Cost = cost;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property Cost in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cost")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Cost is required.")]
        public virtual long Cost
        {
            get
            {
                return this._Cost;
            }
            set
            {
                this.OnCostChanging(value);
                this._Cost = value;
                this.OnCostChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Cost;
        partial void OnCostChanging(long value);
        partial void OnCostChanged();
        /// <summary>
        /// There are no comments for Property Peers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Peers")]
        public virtual global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.Person> Peers
        {
            get
            {
                return this._Peers;
            }
            set
            {
                this.OnPeersChanging(value);
                this._Peers = value;
                this.OnPeersChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.Person> _Peers = new global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.Person>();
        partial void OnPeersChanging(global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.Person> value);
        partial void OnPeersChanged();
    }
}
