//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2024-11-15 12:39:28
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for EventLocation in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EventLocation")]
    public partial class EventLocation : Location
    {
        /// <summary>
        /// There are no comments for Property BuildingInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BuildingInfo")]
        public virtual string BuildingInfo
        {
            get
            {
                return this._BuildingInfo;
            }
            set
            {
                this.OnBuildingInfoChanging(value);
                this._BuildingInfo = value;
                this.OnBuildingInfoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BuildingInfo;
        partial void OnBuildingInfoChanging(string value);
        partial void OnBuildingInfoChanged();
    }
}
