//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/13/2024 12:10:48
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Photo as global::FluentUI.TripPin.Model.PhotoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.PhotoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Photo> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.PhotoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Photo as global::FluentUI.TripPin.Model.PhotoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::FluentUI.TripPin.Model.PhotoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Photo> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::FluentUI.TripPin.Model.PhotoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Person as global::FluentUI.TripPin.Model.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.PersonSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Person as global::FluentUI.TripPin.Model.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="userName">The value of userName</param>
        public static global::FluentUI.TripPin.Model.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> _source,
            string userName)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "UserName", userName }
            };
            return new global::FluentUI.TripPin.Model.PersonSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Airline as global::FluentUI.TripPin.Model.AirlineSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.AirlineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Airline> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.AirlineSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Airline as global::FluentUI.TripPin.Model.AirlineSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="airlineCode">The value of airlineCode</param>
        public static global::FluentUI.TripPin.Model.AirlineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Airline> _source,
            string airlineCode)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "AirlineCode", airlineCode }
            };
            return new global::FluentUI.TripPin.Model.AirlineSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Airport as global::FluentUI.TripPin.Model.AirportSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.AirportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Airport> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.AirportSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Airport as global::FluentUI.TripPin.Model.AirportSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="icaoCode">The value of icaoCode</param>
        public static global::FluentUI.TripPin.Model.AirportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Airport> _source,
            string icaoCode)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "IcaoCode", icaoCode }
            };
            return new global::FluentUI.TripPin.Model.AirportSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.PlanItem as global::FluentUI.TripPin.Model.PlanItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.PlanItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.PlanItem> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.PlanItemSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.PlanItem as global::FluentUI.TripPin.Model.PlanItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="planItemId">The value of planItemId</param>
        public static global::FluentUI.TripPin.Model.PlanItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.PlanItem> _source,
            int planItemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PlanItemId", planItemId }
            };
            return new global::FluentUI.TripPin.Model.PlanItemSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.PublicTransportation as global::FluentUI.TripPin.Model.PublicTransportationSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.PublicTransportationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.PublicTransportation> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.PublicTransportationSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.PublicTransportation as global::FluentUI.TripPin.Model.PublicTransportationSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="planItemId">The value of planItemId</param>
        public static global::FluentUI.TripPin.Model.PublicTransportationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.PublicTransportation> _source,
            int planItemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PlanItemId", planItemId }
            };
            return new global::FluentUI.TripPin.Model.PublicTransportationSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::FluentUI.TripPin.Model.PlanItem to its derived type global::FluentUI.TripPin.Model.PublicTransportation
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::FluentUI.TripPin.Model.PublicTransportationSingle CastToPublicTransportation(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.PlanItem> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.PublicTransportation> query = _source.CastTo<global::FluentUI.TripPin.Model.PublicTransportation>();
            return new global::FluentUI.TripPin.Model.PublicTransportationSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Flight as global::FluentUI.TripPin.Model.FlightSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.FlightSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Flight> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.FlightSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Flight as global::FluentUI.TripPin.Model.FlightSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="planItemId">The value of planItemId</param>
        public static global::FluentUI.TripPin.Model.FlightSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Flight> _source,
            int planItemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PlanItemId", planItemId }
            };
            return new global::FluentUI.TripPin.Model.FlightSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::FluentUI.TripPin.Model.PublicTransportation to its derived type global::FluentUI.TripPin.Model.Flight
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::FluentUI.TripPin.Model.FlightSingle CastToFlight(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.PublicTransportation> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.Flight> query = _source.CastTo<global::FluentUI.TripPin.Model.Flight>();
            return new global::FluentUI.TripPin.Model.FlightSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Cast an entity of type global::FluentUI.TripPin.Model.PlanItem to its derived type global::FluentUI.TripPin.Model.Flight
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::FluentUI.TripPin.Model.FlightSingle CastToFlight(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.PlanItem> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.Flight> query = _source.CastTo<global::FluentUI.TripPin.Model.Flight>();
            return new global::FluentUI.TripPin.Model.FlightSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Event as global::FluentUI.TripPin.Model.EventSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.EventSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Event> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.EventSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Event as global::FluentUI.TripPin.Model.EventSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="planItemId">The value of planItemId</param>
        public static global::FluentUI.TripPin.Model.EventSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Event> _source,
            int planItemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PlanItemId", planItemId }
            };
            return new global::FluentUI.TripPin.Model.EventSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::FluentUI.TripPin.Model.PlanItem to its derived type global::FluentUI.TripPin.Model.Event
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::FluentUI.TripPin.Model.EventSingle CastToEvent(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.PlanItem> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.Event> query = _source.CastTo<global::FluentUI.TripPin.Model.Event>();
            return new global::FluentUI.TripPin.Model.EventSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Trip as global::FluentUI.TripPin.Model.TripSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::FluentUI.TripPin.Model.TripSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Trip> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::FluentUI.TripPin.Model.TripSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::FluentUI.TripPin.Model.Trip as global::FluentUI.TripPin.Model.TripSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="tripId">The value of tripId</param>
        public static global::FluentUI.TripPin.Model.TripSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Trip> _source,
            int tripId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "TripId", tripId }
            };
            return new global::FluentUI.TripPin.Model.TripSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// There are no comments for GetFavoriteAirline in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetFavoriteAirline")]
        public static global::FluentUI.TripPin.Model.AirlineSingle GetFavoriteAirline(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.Person> _source)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::FluentUI.TripPin.Model.AirlineSingle(_source.CreateFunctionQuerySingle<global::FluentUI.TripPin.Model.Airline>("Microsoft.OData.SampleService.Models.TripPin.GetFavoriteAirline", true));
        }
        /// <summary>
        /// There are no comments for GetInvolvedPeople in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetInvolvedPeople")]
        public static global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> GetInvolvedPeople(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.Trip> _source)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return _source.CreateFunctionQuery<global::FluentUI.TripPin.Model.Person>("Microsoft.OData.SampleService.Models.TripPin.GetInvolvedPeople", true);
        }
        /// <summary>
        /// There are no comments for GetFriendsTrips in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetFriendsTrips")]
        public static global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Trip> GetFriendsTrips(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.Person> _source, string userName)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return _source.CreateFunctionQuery<global::FluentUI.TripPin.Model.Trip>("Microsoft.OData.SampleService.Models.TripPin.GetFriendsTrips", true, new global::Microsoft.OData.Client.UriOperationParameter("userName", userName));
        }
        /// <summary>
        /// There are no comments for ShareTrip in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShareTrip")]
        public static global::Microsoft.OData.Client.DataServiceActionQuery ShareTrip(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::FluentUI.TripPin.Model.Person> _source, string userName, int tripId)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery(_source.Context, _source.AppendRequestUri("Microsoft.OData.SampleService.Models.TripPin.ShareTrip"), new global::Microsoft.OData.Client.BodyOperationParameter("userName", userName),
                    new global::Microsoft.OData.Client.BodyOperationParameter("tripId", tripId));
        }
    }
}
