//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2024-11-15 12:39:28
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for Feature in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Feature")]
    public enum Feature
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Feature1")]
        Feature1 = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Feature2")]
        Feature2 = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Feature3")]
        Feature3 = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Feature4")]
        Feature4 = 3
    }
}
