//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2024-11-15 12:39:28
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for ManagerSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ManagerSingle")]
    public partial class ManagerSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Manager>
    {
        /// <summary>
        /// Initialize a new ManagerSingle object.
        /// </summary>
        public ManagerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ManagerSingle object.
        /// </summary>
        public ManagerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ManagerSingle object.
        /// </summary>
        public ManagerSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Manager> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for DirectReports in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DirectReports")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> DirectReports
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._DirectReports == null))
                {
                    this._DirectReports = Context.CreateQuery<global::FluentUI.TripPin.Model.Person>(GetPath("DirectReports"));
                }
                return this._DirectReports;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> _DirectReports;
        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Friends")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> Friends
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Friends == null))
                {
                    this._Friends = Context.CreateQuery<global::FluentUI.TripPin.Model.Person>(GetPath("Friends"));
                }
                return this._Friends;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> _Friends;
        /// <summary>
        /// There are no comments for BestFriend in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BestFriend")]
        public virtual global::FluentUI.TripPin.Model.PersonSingle BestFriend
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BestFriend == null))
                {
                    this._BestFriend = new global::FluentUI.TripPin.Model.PersonSingle(this.Context, GetPath("BestFriend"));
                }
                return this._BestFriend;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::FluentUI.TripPin.Model.PersonSingle _BestFriend;
        /// <summary>
        /// There are no comments for Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Trips")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Trip> Trips
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Trips == null))
                {
                    this._Trips = Context.CreateQuery<global::FluentUI.TripPin.Model.Trip>(GetPath("Trips"));
                }
                return this._Trips;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Trip> _Trips;
    }
    /// <summary>
    /// There are no comments for Manager in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("UserName")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Manager")]
    public partial class Manager : Person
    {
        /// <summary>
        /// Create a new Manager object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="gender">Initial value of Gender.</param>
        /// <param name="favoriteFeature">Initial value of FavoriteFeature.</param>
        /// <param name="budget">Initial value of Budget.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Manager CreateManager(string userName, string firstName, global::FluentUI.TripPin.Model.PersonGender gender, global::FluentUI.TripPin.Model.Feature favoriteFeature, long budget)
        {
            Manager manager = new Manager();
            manager.UserName = userName;
            manager.FirstName = firstName;
            manager.Gender = gender;
            manager.FavoriteFeature = favoriteFeature;
            manager.Budget = budget;
            return manager;
        }
        /// <summary>
        /// There are no comments for Property Budget in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Budget")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Budget is required.")]
        public virtual long Budget
        {
            get
            {
                return this._Budget;
            }
            set
            {
                this.OnBudgetChanging(value);
                this._Budget = value;
                this.OnBudgetChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Budget;
        partial void OnBudgetChanging(long value);
        partial void OnBudgetChanged();
        /// <summary>
        /// There are no comments for Property BossOffice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BossOffice")]
        public virtual global::FluentUI.TripPin.Model.Location BossOffice
        {
            get
            {
                return this._BossOffice;
            }
            set
            {
                this.OnBossOfficeChanging(value);
                this._BossOffice = value;
                this.OnBossOfficeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::FluentUI.TripPin.Model.Location _BossOffice;
        partial void OnBossOfficeChanging(global::FluentUI.TripPin.Model.Location value);
        partial void OnBossOfficeChanged();
        /// <summary>
        /// There are no comments for Property DirectReports in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DirectReports")]
        public virtual global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.Person> DirectReports
        {
            get
            {
                return this._DirectReports;
            }
            set
            {
                this.OnDirectReportsChanging(value);
                this._DirectReports = value;
                this.OnDirectReportsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.Person> _DirectReports = new global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.Person>();
        partial void OnDirectReportsChanging(global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.Person> value);
        partial void OnDirectReportsChanged();
    }
}
