//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2024-11-15 12:39:28
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for PlanItemSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PlanItemSingle")]
    public partial class PlanItemSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PlanItem>
    {
        /// <summary>
        /// Initialize a new PlanItemSingle object.
        /// </summary>
        public PlanItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PlanItemSingle object.
        /// </summary>
        public PlanItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PlanItemSingle object.
        /// </summary>
        public PlanItemSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PlanItem> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PlanItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PlanItemId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PlanItemId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PlanItem")]
    public partial class PlanItem : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new PlanItem object.
        /// </summary>
        /// <param name="planItemId">Initial value of PlanItemId.</param>
        /// <param name="startsAt">Initial value of StartsAt.</param>
        /// <param name="endsAt">Initial value of EndsAt.</param>
        /// <param name="duration">Initial value of Duration.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PlanItem CreatePlanItem(int planItemId, global::System.DateTimeOffset startsAt, global::System.DateTimeOffset endsAt, global::System.TimeSpan duration)
        {
            PlanItem planItem = new PlanItem();
            planItem.PlanItemId = planItemId;
            planItem.StartsAt = startsAt;
            planItem.EndsAt = endsAt;
            planItem.Duration = duration;
            return planItem;
        }
        /// <summary>
        /// There are no comments for Property PlanItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PlanItemId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PlanItemId is required.")]
        public virtual int PlanItemId
        {
            get
            {
                return this._PlanItemId;
            }
            set
            {
                this.OnPlanItemIdChanging(value);
                this._PlanItemId = value;
                this.OnPlanItemIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _PlanItemId;
        partial void OnPlanItemIdChanging(int value);
        partial void OnPlanItemIdChanged();
        /// <summary>
        /// There are no comments for Property ConfirmationCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ConfirmationCode")]
        public virtual string ConfirmationCode
        {
            get
            {
                return this._ConfirmationCode;
            }
            set
            {
                this.OnConfirmationCodeChanging(value);
                this._ConfirmationCode = value;
                this.OnConfirmationCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ConfirmationCode;
        partial void OnConfirmationCodeChanging(string value);
        partial void OnConfirmationCodeChanged();
        /// <summary>
        /// There are no comments for Property StartsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StartsAt")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "StartsAt is required.")]
        public virtual global::System.DateTimeOffset StartsAt
        {
            get
            {
                return this._StartsAt;
            }
            set
            {
                this.OnStartsAtChanging(value);
                this._StartsAt = value;
                this.OnStartsAtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _StartsAt;
        partial void OnStartsAtChanging(global::System.DateTimeOffset value);
        partial void OnStartsAtChanged();
        /// <summary>
        /// There are no comments for Property EndsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EndsAt")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EndsAt is required.")]
        public virtual global::System.DateTimeOffset EndsAt
        {
            get
            {
                return this._EndsAt;
            }
            set
            {
                this.OnEndsAtChanging(value);
                this._EndsAt = value;
                this.OnEndsAtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _EndsAt;
        partial void OnEndsAtChanging(global::System.DateTimeOffset value);
        partial void OnEndsAtChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Duration")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Duration is required.")]
        public virtual global::System.TimeSpan Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.TimeSpan _Duration;
        partial void OnDurationChanging(global::System.TimeSpan value);
        partial void OnDurationChanged();
    }
}
