//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2024-11-15 12:39:28
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for PublicTransportationSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PublicTransportationSingle")]
    public partial class PublicTransportationSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PublicTransportation>
    {
        /// <summary>
        /// Initialize a new PublicTransportationSingle object.
        /// </summary>
        public PublicTransportationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PublicTransportationSingle object.
        /// </summary>
        public PublicTransportationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PublicTransportationSingle object.
        /// </summary>
        public PublicTransportationSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PublicTransportation> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PublicTransportation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PlanItemId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PlanItemId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PublicTransportation")]
    public partial class PublicTransportation : PlanItem
    {
        /// <summary>
        /// Create a new PublicTransportation object.
        /// </summary>
        /// <param name="planItemId">Initial value of PlanItemId.</param>
        /// <param name="startsAt">Initial value of StartsAt.</param>
        /// <param name="endsAt">Initial value of EndsAt.</param>
        /// <param name="duration">Initial value of Duration.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PublicTransportation CreatePublicTransportation(int planItemId, global::System.DateTimeOffset startsAt, global::System.DateTimeOffset endsAt, global::System.TimeSpan duration)
        {
            PublicTransportation publicTransportation = new PublicTransportation();
            publicTransportation.PlanItemId = planItemId;
            publicTransportation.StartsAt = startsAt;
            publicTransportation.EndsAt = endsAt;
            publicTransportation.Duration = duration;
            return publicTransportation;
        }
        /// <summary>
        /// There are no comments for Property SeatNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SeatNumber")]
        public virtual string SeatNumber
        {
            get
            {
                return this._SeatNumber;
            }
            set
            {
                this.OnSeatNumberChanging(value);
                this._SeatNumber = value;
                this.OnSeatNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SeatNumber;
        partial void OnSeatNumberChanging(string value);
        partial void OnSeatNumberChanged();
    }
}
