//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2024-11-15 12:39:28
namespace FluentUI.TripPin.Model
{
    /// <summary>
    /// There are no comments for TripSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TripSingle")]
    public partial class TripSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Trip>
    {
        /// <summary>
        /// Initialize a new TripSingle object.
        /// </summary>
        public TripSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TripSingle object.
        /// </summary>
        public TripSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TripSingle object.
        /// </summary>
        public TripSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Trip> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for PlanItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PlanItems")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.PlanItem> PlanItems
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PlanItems == null))
                {
                    this._PlanItems = Context.CreateQuery<global::FluentUI.TripPin.Model.PlanItem>(GetPath("PlanItems"));
                }
                return this._PlanItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.PlanItem> _PlanItems;
    }
    /// <summary>
    /// There are no comments for Trip in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TripId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("TripId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Trip")]
    public partial class Trip : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Trip object.
        /// </summary>
        /// <param name="tripId">Initial value of TripId.</param>
        /// <param name="shareId">Initial value of ShareId.</param>
        /// <param name="budget">Initial value of Budget.</param>
        /// <param name="startsAt">Initial value of StartsAt.</param>
        /// <param name="endsAt">Initial value of EndsAt.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Trip CreateTrip(int tripId, global::System.Guid shareId, float budget, global::System.DateTimeOffset startsAt, global::System.DateTimeOffset endsAt)
        {
            Trip trip = new Trip();
            trip.TripId = tripId;
            trip.ShareId = shareId;
            trip.Budget = budget;
            trip.StartsAt = startsAt;
            trip.EndsAt = endsAt;
            return trip;
        }
        /// <summary>
        /// There are no comments for Property TripId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TripId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TripId is required.")]
        public virtual int TripId
        {
            get
            {
                return this._TripId;
            }
            set
            {
                this.OnTripIdChanging(value);
                this._TripId = value;
                this.OnTripIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _TripId;
        partial void OnTripIdChanging(int value);
        partial void OnTripIdChanged();
        /// <summary>
        /// There are no comments for Property ShareId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShareId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ShareId is required.")]
        public virtual global::System.Guid ShareId
        {
            get
            {
                return this._ShareId;
            }
            set
            {
                this.OnShareIdChanging(value);
                this._ShareId = value;
                this.OnShareIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _ShareId;
        partial void OnShareIdChanging(global::System.Guid value);
        partial void OnShareIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Budget in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Budget")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Budget is required.")]
        public virtual float Budget
        {
            get
            {
                return this._Budget;
            }
            set
            {
                this.OnBudgetChanging(value);
                this._Budget = value;
                this.OnBudgetChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private float _Budget;
        partial void OnBudgetChanging(float value);
        partial void OnBudgetChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Tags in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Tags")]
        public virtual global::System.Collections.ObjectModel.Collection<string> Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                this.OnTagsChanging(value);
                this._Tags = value;
                this.OnTagsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<string> _Tags = new global::System.Collections.ObjectModel.Collection<string>();
        partial void OnTagsChanging(global::System.Collections.ObjectModel.Collection<string> value);
        partial void OnTagsChanged();
        /// <summary>
        /// There are no comments for Property StartsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StartsAt")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "StartsAt is required.")]
        public virtual global::System.DateTimeOffset StartsAt
        {
            get
            {
                return this._StartsAt;
            }
            set
            {
                this.OnStartsAtChanging(value);
                this._StartsAt = value;
                this.OnStartsAtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _StartsAt;
        partial void OnStartsAtChanging(global::System.DateTimeOffset value);
        partial void OnStartsAtChanged();
        /// <summary>
        /// There are no comments for Property EndsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EndsAt")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EndsAt is required.")]
        public virtual global::System.DateTimeOffset EndsAt
        {
            get
            {
                return this._EndsAt;
            }
            set
            {
                this.OnEndsAtChanging(value);
                this._EndsAt = value;
                this.OnEndsAtChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _EndsAt;
        partial void OnEndsAtChanging(global::System.DateTimeOffset value);
        partial void OnEndsAtChanged();
        /// <summary>
        /// There are no comments for Property PlanItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PlanItems")]
        public virtual global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.PlanItem> PlanItems
        {
            get
            {
                return this._PlanItems;
            }
            set
            {
                this.OnPlanItemsChanging(value);
                this._PlanItems = value;
                this.OnPlanItemsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.PlanItem> _PlanItems = new global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.PlanItem>();
        partial void OnPlanItemsChanging(global::System.Collections.ObjectModel.Collection<global::FluentUI.TripPin.Model.PlanItem> value);
        partial void OnPlanItemsChanged();
        /// <summary>
        /// There are no comments for GetInvolvedPeople in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetInvolvedPeople")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::FluentUI.TripPin.Model.Person> GetInvolvedPeople()
        {
            global::System.Uri requestUri;
            Context.TryGetUri(this, out requestUri);
            return this.Context.CreateFunctionQuery<global::FluentUI.TripPin.Model.Person>(string.Join("/", global::System.Linq.Enumerable.Select(global::System.Linq.Enumerable.Skip(requestUri.Segments, this.Context.BaseUri.Segments.Length), s => s.Trim('/'))), "Trippin.GetInvolvedPeople", false);
        }
    }
}
